

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import { Mode as TextMode } from './text';
import { CspHighlightRules } from './csp_highlight_rules';
import oop from '../lib/oop';

var Mode = function() {
    this.HighlightRules = CspHighlightRules;
};

oop.inherits(Mode, TextMode);

(function() {
    this.$id = "ace/mode/csp";
}).call(Mode.prototype);

export { Mode };
