

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop';
import { Mode as CMode } from './c_cpp';
import { DartHighlightRules } from './dart_highlight_rules';
import { FoldMode as CStyleFoldMode } from './folding/cstyle';

var Mode = function() {
    CMode.call(this);
    this.HighlightRules = DartHighlightRules;
    this.foldingRules = new CStyleFoldMode();
};
oop.inherits(Mode, CMode);

(function() { 
    this.lineCommentStart = "//";
    this.blockComment = {start: "/*", end: "*/"};
    this.$id = "ace/mode/dart";
}).call(Mode.prototype);

export { Mode };
