

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop';
import { Mode as TextMode } from './text';
import { ElmHighlightRules as HighlightRules } from './elm_highlight_rules';
import { FoldMode } from './folding/cstyle';

var Mode = function() {
    this.HighlightRules = HighlightRules;
    this.foldingRules = new FoldMode();
    this.$behaviour = this.$defaultBehaviour;
};
oop.inherits(Mode, TextMode);

(function() {
    this.lineCommentStart = "--";
    this.blockComment = {start: "{-", end: "-}", nestable: true};
    // Extra logic goes here.
    this.$id = "ace/mode/elm";
}).call(Mode.prototype);

export { Mode };
