

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop';
import { Mode as TextMode } from './text';
import { ForthHighlightRules } from './forth_highlight_rules';
import { FoldMode } from './folding/cstyle';

var Mode = function() {
    this.HighlightRules = ForthHighlightRules;
    this.foldingRules = new FoldMode();
    this.$behaviour = this.$defaultBehaviour;
};
oop.inherits(Mode, TextMode);

(function() {
    this.lineCommentStart = "--";
    this.blockComment = null;
    this.$id = "ace/mode/forth";
}).call(Mode.prototype);

export { Mode };
