

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop.js';
import { Mode as TextMode } from './text.js';
import { FSLHighlightRules } from './fsl_highlight_rules.js';

// TODO: pick appropriate fold mode
import { FoldMode } from './folding/cstyle.js';

var Mode = function() {
    this.HighlightRules = FSLHighlightRules;
    this.foldingRules = new FoldMode();
};
oop.inherits(Mode, TextMode);

(function() {
    this.lineCommentStart = "//";
    this.blockComment = {start: "/*", end: "*/"};
    // Extra logic goes here.
    this.$id = "ace/mode/fsl";
}).call(Mode.prototype);

export { Mode };
