

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop';
import { Mode as TextMode } from './text';
import { KotlinHighlightRules } from './kotlin_highlight_rules';
import { CstyleBehaviour } from './behaviour/cstyle';
import { FoldMode } from './folding/cstyle';

var Mode = function() {
    this.HighlightRules = KotlinHighlightRules;
    this.foldingRules = new FoldMode();
    this.$behaviour = new CstyleBehaviour();
};
oop.inherits(Mode, TextMode);

(function() {
    // this.lineCommentStart = ""/\\*"";
    // this.blockComment = {start: ""/*"", end: ""*/""};
    // Extra logic goes here.
    this.$id = "ace/mode/kotlin";
}).call(Mode.prototype);

export { Mode };
