

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop';
import { Mode as TextMode } from './text';
import { Tokenizer } from '../tokenizer';
import { LogtalkHighlightRules } from './logtalk_highlight_rules';

// TODO: pick appropriate fold mode
import { FoldMode } from './folding/cstyle';

var Mode = function() {
    this.HighlightRules = LogtalkHighlightRules;
    this.foldingRules = new FoldMode();
    this.$behaviour = this.$defaultBehaviour;
};
oop.inherits(Mode, TextMode);

(function() {
    this.lineCommentStart = "%";
    this.blockComment = {start: "/*", end: "*/"};
    this.$id = "ace/mode/logtalk";
}).call(Mode.prototype);

export { Mode };
