

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop';
import { Mode as CMode } from './c_cpp';
import { NixHighlightRules } from './nix_highlight_rules';
import { FoldMode as CStyleFoldMode } from './folding/cstyle';

var Mode = function() {
    CMode.call(this);
    this.HighlightRules = NixHighlightRules;
    this.foldingRules = new CStyleFoldMode();
    this.$behaviour = this.$defaultBehaviour;
};
oop.inherits(Mode, CMode);

(function() { 
    this.lineCommentStart = "#";
    this.blockComment = {start: "/*", end: "*/"};
    this.$id = "ace/mode/nix";
}).call(Mode.prototype);

export { Mode };
