

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop';
import { Mode as TextMode } from './text';
import { ObjectiveCHighlightRules } from './objectivec_highlight_rules';
import { FoldMode as CStyleFoldMode } from './folding/cstyle';

var Mode = function() {
    this.HighlightRules = ObjectiveCHighlightRules;
    this.foldingRules = new CStyleFoldMode();
    this.$behaviour = this.$defaultBehaviour;
};
oop.inherits(Mode, TextMode);

(function() {
    this.lineCommentStart = "//";
    this.blockComment = {start: "/*", end: "*/"};
    this.$id = "ace/mode/objectivec";
}).call(Mode.prototype);

export { Mode };
