

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop.js';
import { Mode as TextMode } from './text.js';
import { SPARQLHighlightRules } from './sparql_highlight_rules.js';

// TODO: pick appropriate fold mode
import { FoldMode } from './folding/cstyle.js';

var Mode = function() {
    this.HighlightRules = SPARQLHighlightRules;
    this.foldingRules = new FoldMode();
};
oop.inherits(Mode, TextMode);

(function() {
    // this.lineCommentStart = ""#"";
    // Extra logic goes here.
    this.$id = "ace/mode/sparql";
}).call(Mode.prototype);

export { Mode };
