

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop';
import { Mode as TextMode } from './text';
import { TurtleHighlightRules } from './turtle_highlight_rules';

// TODO: pick appropriate fold mode
import { FoldMode } from './folding/cstyle';

var Mode = function() {
    this.HighlightRules = TurtleHighlightRules;
    this.foldingRules = new FoldMode();
};
oop.inherits(Mode, TextMode);

(function() {
    // this.lineCommentStart = ""#"";
    // Extra logic goes here.
    this.$id = "ace/mode/turtle";
}).call(Mode.prototype);

export { Mode };
