

/*
  THIS FILE WAS AUTOGENERATED BY mode.tmpl.js
*/

"use strict";

import oop from '../lib/oop.js';
import { Mode as TextMode } from './text.js';
import { ZeekHighlightRules } from './zeek_highlight_rules.js';
import { FoldMode } from './folding/cstyle.js';

var Mode = function() {
    this.HighlightRules = ZeekHighlightRules;
    this.foldingRules = new FoldMode();
};
oop.inherits(Mode, TextMode);

(function() {
    this.lineCommentStart = "#";
    // Extra logic goes here.
    this.$id = "ace/mode/zeek";
}).call(Mode.prototype);

export { Mode };
